# mostly taken from github.com/robustirc/bridge
sudo: false

language: go

script:
  # Check whether files are syntactically correct.
  - "gofmt -l $(find . -name '*.go' | tr '\\n' ' ') >/dev/null"
  # Check whether files were not gofmt'ed.
  - "gosrc=$(find . -name '*.go' | tr '\\n' ' '); [ $(gofmt -l $gosrc 2>&- | wc -l) -eq 0 ] || (echo 'gofmt was not run on these files:'; gofmt -l $gosrc 2>&-; false)"
  # Run go vet for further checking.
  - go vet github.com/pseyfert/go-workpool
  # Run tests (output validation)
  - go run github.com/pseyfert/go-workpool/toy -j 1 -N 10
  - go run github.com/pseyfert/go-workpool/toy -j 4 -N 1
  - go run github.com/pseyfert/go-workpool/toy -j 4 -N 4
  - go run github.com/pseyfert/go-workpool/toy -j 2 -N 7
